spring:
  data:
    mongodb:
      host: 192.168.24.53
      port: 27017
      database: test_insert
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.24.53:3306/ckshop?&serverTimezone=GMT%2B8
      username: root
      password: ckc@ckc

#¥Ú”°sql
logging:
  level:
    com.shield: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shield.domain
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    id-type: 3
    field-strategy: 2
    db-column-underline: true
